In [1]:
pip install numpy -q

In [2]:
pip install pandas -q

In [4]:
pip install scikit-learn -q

In [5]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv


## Bibliotecas

In [6]:
import numpy as np
from sklearn.metrics import adjusted_rand_score
import pandas as pd

## Tratamento de dados

### Dataset

In [8]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Verificação das classes

In [9]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

### Verificação das colunas

In [10]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

### Transformação das classes

In [11]:
df.drop("Id", axis=1, inplace=True)
df["Species"].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}, inplace=True)
df.head()

<ipython-input-11-04874d04feea>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Species"].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}, inplace=True)
<ipython-input-11-04874d04feea>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"].replace({"Iris-setosa": 0

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

### Verificação das classes

In [12]:
df["Species"].unique()

array([0, 1, 2])

### Renomeação das colunas

In [13]:
df.columns = ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", "Class"]
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Class
0            5.1           3.5            1.4           0.2      0
1            4.9           3.0            1.4           0.2      0
2            4.7           3.2            1.3           0.2      0
3            4.6           3.1            1.5           0.2      0
4            5.0           3.6            1.4           0.2      0

### Separação das classes do dataset

In [14]:
labels = df["Class"].values
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
df.drop("Class", axis=1, inplace=True)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

### Conversão dos dados em uma matriz

In [16]:
dados = df.to_numpy()
dados

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Clusterização

### Inicialização da matriz de pertinência

In [ ]:
def inicializacao_matriz_pertinencia(num_amostras, num_clusters):
    matriz_pertinencia = np.random.rand(num_amostras, num_clusters)  # Gera matriz aleatória inicial
    matriz_pertinencia = matriz_pertinencia / matriz_pertinencia.sum(axis=1, keepdims=True)  # Normaliza para garantir que a soma dos graus de pertinência seja 1
    return matriz_pertinencia

### Atualização dos medoids (Corrigir)

In [ ]:
def atualizacao_medoids(dados, matriz_pertinencia, m):
    """
    Atualiza os medoids com base na matriz de pertinência.
    Escolhe o ponto que minimiza a soma das distâncias ponderadas por pertinência.
    """
    num_clusters = matriz_pertinencia.shape[1]
    medoids = np.zeros((num_clusters, dados.shape[1]))

    for i in range(num_clusters):
        pertinencias_m = matriz_pertinencia[:, i] ** m
        distancias_somadas = np.sum(pertinencias_m[:, np.newaxis] * np.linalg.norm(dados[:, np.newaxis] - dados, axis=2), axis=0)

        medoids[i] = dados[np.argmin(distancias_somadas)]

    return medoids

### Atualização da matriz de pertinência (Corrigir)

In [ ]:
def atualizacao_matriz_pertinencia(dados, medoids, m):
    # Calcula as distâncias euclidianas entre cada ponto e os medoids
    matriz_distancias = np.linalg.norm(dados[:, np.newaxis] - medoids, axis=2)  # d(x_k, v_i)

    # Evita divisões por zero ajustando qualquer distância zero para um valor mínimo positivo
    matriz_distancias = np.fmax(matriz_distancias, np.finfo(np.float64).eps)

    # Inicializa a matriz de pertinência
    matriz_pertinencia_atualizada = np.zeros((dados.shape[0], medoids.shape[0]))

    # Atualiza os graus de pertinência com base na fórmula
    for i in range(medoids.shape[0]):  # Para cada medoid
        denominador = np.sum((matriz_distancias[:, i, np.newaxis] / matriz_distancias) ** (1 / (m - 1)), axis=1)
        matriz_pertinencia_atualizada[:, i] = 1 / denominador

    return matriz_pertinencia_atualizada

### FCMdd (Corrigir)

In [ ]:
def fuzzy_c_medoids(dados, num_clusters, m=2, max_iter=1000, erro=1e-5):
    """
    Implementação do algoritmo Fuzzy C-Medoids.

    Parâmetros:
    dados -- array com os dados (observações)
    num_clusters -- número de clusters
    m -- parâmetro de fuzzificação (m > 1)
    max_iter -- número máximo de iterações
    erro -- critério de convergência

    Retorna:
    medoids -- os medoids finais
    matriz_pertinencia -- a matriz de pertinência final
    """
    num_amostras = dados.shape[0]

    matriz_pertinencia = inicializacao_matriz_pertinencia(num_amostras, num_clusters)

    for _ in range(max_iter):
        medoids = atualizacao_medoids(dados, matriz_pertinencia, m)

        nova_matriz_pertinencia = atualizacao_matriz_pertinencia(dados, medoids, m)

        if np.linalg.norm(nova_matriz_pertinencia - matriz_pertinencia) < erro:
            break

        matriz_pertinencia = nova_matriz_pertinencia

    return medoids, matriz_pertinencia

### Índice de Rand Ajustado

In [ ]:
def indice_rand(labels, predicted_labels):
    return adjusted_rand_score(labels, predicted_labels)

### Experimento de Monte Carlo

In [20]:
def experimento_monte_carlo(dados, labels, num_clusters, num_trials):
    indices_rand = []

    for trial in range(num_trials):
        print(trial)
        medoids, matriz_pertinencia = fuzzy_c_medoids(dados, num_clusters)
        predicted_labels = np.argmax(matriz_pertinencia, axis=1)
        idx_rand = indice_rand(labels, predicted_labels)
        indices_rand.append(idx_rand)

    mean_rand_index = np.mean(indices_rand)
    std_rand_index = np.std(indices_rand)

    return mean_rand_index, std_rand_index


## Execução do método

In [22]:
num_clusters = 3
num_trials = 100
media_indice_rand, dp_indice_rand = experimento_monte_carlo(dados, labels, num_clusters, num_trials)

print(f"Monte Carlo FCMdd Clustering Results ({num_trials} trials)")
print(f"Mean Rand Index: {media_indice_rand:.4f}") # Resultado esperado: 0.3589
print(f"Standard Deviation of Rand Index: {dp_indice_rand:.4f}")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
Monte Carlo FCMdd Clustering Results (100 trials)
Mean Rand Index: 0.4230
Standard Deviation of Rand Index: 0.0956
