In [1]:
pip install numpy -q

In [2]:
pip install pandas -q

In [3]:
pip install scikit-learn -q

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv


## Bibliotecas

In [5]:
import numpy as np
from sklearn.metrics import adjusted_rand_score
import pandas as pd

## Tratamento de dados

### Dataset

In [6]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Verificação das classes

In [7]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

### Verificação das colunas

In [8]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

### Transformação das classes

In [9]:
df.drop("Id", axis=1, inplace=True)
df["Species"].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}, inplace=True)
df.head()

<ipython-input-9-04874d04feea>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Species"].replace({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}, inplace=True)
<ipython-input-9-04874d04feea>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"].replace({"Iris-setosa": 0, 

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

### Verificação das classes

In [10]:
df["Species"].unique()

array([0, 1, 2])

### Renomeação das colunas

In [11]:
df.columns = ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", "Class"]
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Class
0            5.1           3.5            1.4           0.2      0
1            4.9           3.0            1.4           0.2      0
2            4.7           3.2            1.3           0.2      0
3            4.6           3.1            1.5           0.2      0
4            5.0           3.6            1.4           0.2      0

### Separação das classes do dataset

In [12]:
labels = df["Class"].values
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
df.drop("Class", axis=1, inplace=True)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

### Conversão dos dados em uma matriz

In [14]:
dados = df.to_numpy()
dados

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## Clusterização

### Inicialização da matriz de pertinência

In [27]:
def inicializacao_matriz_pertinencia(num_amostras, num_clusters):
    matriz_pertinencia = np.random.rand(num_amostras, num_clusters)  # Gera matriz aleatória inicial
    matriz_pertinencia = matriz_pertinencia / matriz_pertinencia.sum(axis=1, keepdims=True)  # Normaliza para garantir que a soma dos graus de pertinência seja 1
    return matriz_pertinencia

### Atualização dos medoids (Corrigir)

In [34]:
def atualizacao_medoids(dados, matriz_pertinencia, m):
    num_clusters = matriz_pertinencia.shape[1]
    medoids = np.zeros((num_clusters, dados.shape[1]))

    for i in range(num_clusters):
        ponderacao = matriz_pertinencia[:, i] ** m
        distancias_total = np.sum(np.linalg.norm(dados[:, np.newaxis] - dados, axis=2) * ponderacao[:, np.newaxis], axis=0)
        medoids[i] = dados[np.argmin(distancias_total)]

    return medoids

### Atualização da matriz de pertinência (Corrigir)

In [36]:
def atualizacao_matriz_pertinencia(dados, medoids, m):
    matriz_distancias = np.linalg.norm(dados[:, np.newaxis] - medoids, axis=2)
    matriz_distancias = np.fmax(matriz_distancias, np.finfo(np.float64).eps)
    matriz_pertinencia_atualizada = np.zeros((dados.shape[0], medoids.shape[0]))

    for i in range(medoids.shape[0]):
        numerador = matriz_distancias[:, i] ** (1 / (m - 1))
        denominador = np.sum(numerador[:, np.newaxis] / matriz_distancias, axis=1)
        matriz_pertinencia_atualizada[:, i] = 1 / denominador

    return matriz_pertinencia_atualizada

### FCMdd (Corrigir)

In [37]:
def fcmdd(dados, num_clusters, m=2, max_iter=1000, erro=1e-5):
    num_amostras = dados.shape[0]
    matriz_pertinencia = inicializacao_matriz_pertinencia(num_amostras, num_clusters)

    for _ in range(max_iter):
        medoids = atualizacao_medoids(dados, matriz_pertinencia, m)
        nova_matriz_pertinencia = atualizacao_matriz_pertinencia(dados, medoids, m)

        if np.linalg.norm(nova_matriz_pertinencia - matriz_pertinencia) < erro:
            break

        matriz_pertinencia = nova_matriz_pertinencia

    return medoids, matriz_pertinencia

### Índice de Rand Ajustado

In [31]:
def indice_rand(labels, predicted_labels):
    return adjusted_rand_score(labels, predicted_labels)

### Experimento de Monte Carlo

In [32]:
def experimento_monte_carlo(dados, labels, num_clusters, num_trials):
    indices_rand = []

    for trial in range(num_trials):
        medoids, matriz_pertinencia = fcmdd(dados, num_clusters)
        predicted_labels = np.argmax(matriz_pertinencia, axis=1)
        idx_rand = indice_rand(labels, predicted_labels)
        indices_rand.append(idx_rand)

    mean_rand_index = np.mean(indices_rand)
    std_rand_index = np.std(indices_rand)

    return mean_rand_index, std_rand_index


## Execução do método

In [44]:
num_clusters = 3
num_trials = 100
media_indice_rand, dp_indice_rand = experimento_monte_carlo(dados, labels, num_clusters, num_trials)

print(f"Monte Carlo FCMdd Clustering Results ({num_trials} trials)")
print(f"Mean Rand Index: {media_indice_rand:.4f}") # Resultado esperado: 0.3589
print(f"Standard Deviation of Rand Index: {dp_indice_rand:.4f}")

Monte Carlo FCMdd Clustering Results (100 trials)
Mean Rand Index: 0.4156
Standard Deviation of Rand Index: 0.1051
